apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: false
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: ""
      exemplarType: label
      exemplarTraceIdDest: trace_id
      traceExploration: true
      prometheusType: prometheus
      prometheusVersion: "2.51.0"
    version: 1
    uid: prometheus
